# This is the main playbook for deploying Mediahub and its dependencies.
# It includes the roles for ffmpeg, java, mariadb, mediahub, shaka-packager, and tsduck.
---
- name: Install Mediahub WS Servers application and dependencies
  hosts: mediahub_ws_servers
  gather_facts: false
  roles:
#    - ffmpeg
#    - java
    - mariadb # install mariadb + create database + configure user
#    - mediahub # install mediahub-ws+ mediahub-admin
#    - shaka-packager
#    - tsduck