---
# This playbook installs and configures a mariadb server upon mediahub-ws servers.


- name: MariaDB Server Installation
  ansible.builtin.apt:
      name: mariadb-server
      state: present
      update_cache: yes

- name: Ensure the python library for MySQL is installed
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes
 
- name: Ensure that MariaDB Server is started
  service:
      name: mariadb
      state: started

- name: Create the media_hub database
  mysql_db:
    name: media_hub
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

