---
# This playbook installs and configures a mariadb server upon mediahub-ws servers.


- name: MariaDB Server Installation
  ansible.builtin.apt:
      name: mariadb-server
      state: present
 
- name: Ensure MariaDB Server is at the latest version
  apt:
      name: mariadb-server
      state: latest

- name: Ensure the python library for MySQL is installed
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes
 
- name: Ensure that MariaDB Server is started
  service:
      name: mariadb
      state: started

