---
# This role installs and configures mariadb server upon mediahub-ws servers.
# It creates a database named media_hub and a user named media_hub_user.
# The all tables and base records will be created by media_hub webservice application.

- name: MariaDB Server Installation
  ansible.builtin.apt:
      name: mariadb-server
      state: present
      update_cache: yes

- name: Ensure the python library for MySQL is installed
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes
 
- name: Ensure that MariaDB Server is started
  service:
      name: mariadb
      state: started

- name: Create the snow-user
  mysql_user:
    name: snow-mediahub-user
    password: "SNUser@Mediahub1234"
    host: localhost
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create the media_hub database
  mysql_db:
    name: media_hub
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create the media_hub_user
  mysql_user:
    name: media_hub_user
    password: "Medi@Hub1234"
    host: localhost
    priv: 'media_hub.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock


